# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Plants Recommender' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Plants_test1
 
  pod 'DDSpiderChart'

  target 'Plants RecommenderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Plants RecommenderUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
